# Generated by Django 4.1.7 on 2023-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuarioshilo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={},
        ),
        migrations.AlterField(
            model_name='usuarioshilo',
            name='email',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioshilo',
            name='url',
            field=models.CharField(max_length=210),
        ),
    ]
