# Generated by Django 4.1.7 on 2023-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_artista_options_alter_publicidad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
            options={
                'ordering': ['id', 'nombre'],
            },
        ),
    ]
